    mommy.recipe('person', 'model_mommy.Person',
      name = 'John Doe',
      nickname = 'joe',
      age = 18,
      bio = 'Someone in the crowd',
      birthday = date.today(),
      appointment = date.today(),
      blog = 'http://joe.blogspot.com',
      wanted_games_qtd = 4,
    )
